### ISSUE TITLE
Traditional content type

### ISSUE THREAD

**Issue by Anardael** [Anardael/nwchecker#11]
We should add traditional content type. When everyone will submit their solutions but only the latest one would be checked only when content will end. In this case solution will cost depending on how much tests were passed.

**Comment by Entro-yuhim** [comment]
Contest, not content :)

**Comment by Entro-yuhim** [comment]
The way we figured it, it should work like this:

1. Dynamic contest's rating is calculated as it is right now: every time user sumbits the solution, we send it to checker, and then we evaluate checker's result, and if user's solution failed at least one test, his solution is deemed a failure. User may send his solution again, until the contest is going.

2. Static contest's results may be calculated in two various ways: we can allow user to submit unlimited amount of solutions until the contest is over, then send the last one to checker, or every time user submits his solution, his current solution is sent to checker, evaluated, then his current solution overrides the previous solution, losing his previous data, but we never show the user his current result until the contest is over. Which one of these two is prefered?

**Comment by Entro-yuhim** [comment]
Implemented
