### ISSUE TITLE
Create protocol and mock checker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Anardael/nwchecker#2]
```
Create protocol for communication according to requirements and mock checker 
that will randomly put results. This task could be for two peoples.
```

Original issue reported on code.google.com by `anard...@gmail.com` on 18 Dec 2014 at 12:21

**Comment by Anardael** [comment]
This task is still up to date. We need to change checking proceedure to use sockets plug google protocols.

**Comment by Entro-yuhim** [comment]
What is the format of the protobuf message we should send and recieve?

**Comment by Entro-yuhim** [comment]
Kinda added
